module Main where

import Criterion

main = defaultMain [
  bgroup "Alternative" []
  bgroup "Monad" []
  bgroup "Functor" []
  bgroup "MonadPlus" []
  bgroup "Applicative" []
  bgroup "Foldable" []
  bgroup "Traversable" []
  bgroup "IsList" []
  bgroup "Eq" []
  bgroup "Data" []
  bgroup "Ord" []
  bgroup "Read" []
  bgroup "Show" []
  bgroup "Monoid" []
  bgroup "NFData" []
  bgroup "length" []
  bgroup "null" []
  bgroup "(!)" []
  bgroup "(!?)" []
  bgroup "head" []
  bgroup "last" []
  bgroup "unsafeIndex" []
  bgroup "unsafeHead" []
  bgroup "unsafeLast" []
  bgroup "indexM" []
  bgroup "headM" []
  bgroup "lastM" []
  bgroup "unsafeIndexM" []
  bgroup "unsafeHeadM" []
  bgroup "unsafeLastM" []
  bgroup "slice" []
  bgroup "init" []
  bgroup "tail" []
  bgroup "take" []
  bgroup "drop" []
  bgroup "splitAt" []
  bgroup "unsafeSlice" []
  bgroup "unsafeInit" []
  bgroup "unsafeTail" []
  bgroup "unsafeTake" []
  bgroup "unsafeDrop" []
  bgroup "empty" []
  bgroup "singleton" []
  bgroup "replicate" []
  bgroup "generate" []
  bgroup "iterateN" []
  bgroup "replicateM" []
  bgroup "generateM" []
  bgroup "create" []
  bgroup "unfoldr" []
  bgroup "unfoldrN" []
  bgroup "constructN" []
  bgroup "constructrN" []
  bgroup "enumFromN" []
  bgroup "enumFromStepN" []
  bgroup "enumFromTo" []
  bgroup "enumFromThenTo" []
  bgroup "cons" []
  bgroup "snoc" []
  bgroup "(++)" []
  bgroup "concat" []
  bgroup "force" []
  bgroup "(//)" []
  bgroup "update" []
  bgroup "update_" []
  bgroup "unsafeUpd" []
  bgroup "unsafeUpdate" []
  bgroup "unsafeUpdate_" []
  bgroup "accum" []
  bgroup "accumulate" []
  bgroup "unsafeAccum" []
  bgroup "unsafeAccumulate_" []
  bgroup "reverse" []
  bgroup "backpermute" []
  bgroup "unsafeBackpermute" []
  bgroup "modify" []
  bgroup "indexed" []
  bgroup "map" []
  bgroup "imap" []
  bgroup "concatMap" []
  bgroup "mapM" []
  bgroup "imapM" []
  bgroup "mapM_" []
  bgroup "imapM_" []
  bgroup "forM" []
  bgroup "forM_" []
  bgroup "zipWith"
  bgroup "zipWith3"
  bgroup "zipWith4" []
  bgroup "zipWith5" []
  bgroup "zipWith6" []
  bgroup "izipWith" []
  bgroup "izipWith3" []
  bgroup "izipWith4" []
  bgroup "izipWith5" []
  bgroup "izipWith6" []
  bgroup "zip" []
  bgroup "zip3" []
  bgroup "zip4" []
  bgroup "zip5" []
  bgroup "zip6" []
  bgroup "zipWithM" []
  bgroup "izipWithM" []
  bgroup "zipWithM_" []
  bgroup "izipWithM_" []
  bgroup "unzip" []
  bgroup "unzip3" []
  bgroup "unzip4" []
  bgroup "unzip5" []
  bgroup "unzip6" []
  bgroup "filter" []
  bgroup "ifilter" []
  bgroup "filterM" []
  bgroup "takeWhile" []
  bgroup "dropWhile" []
  bgroup "partition" []
  bgroup "unstablePartition" []
  bgroup "span" []
  bgroup "break" []
  bgroup "elem" []
  bgroup "notElem" []
  bgroup "find" []
  bgroup "findIndex" []
  bgroup "elemIndex" []
  bgroup "elemIndices" []
  bgroup "foldl" []
  bgroup "foldl1" []
  bgroup "foldl'" []
  bgroup "foldl1'" []
  bgroup "foldr" []
  bgroup "foldr1" []
  bgroup "foldr'" []
  bgroup "foldr1'" []
  bgroup "ifoldl" []
  bgroup "ifoldl'" []
  bgroup "ifoldr" []
  bgroup "ifoldr'" []
  bgroup "all" []
  bgroup "any" []
  bgroup "and" []
  bgroup "or" []
  bgroup "sum" []
  bgroup "product" []
  bgroup "maximum" []
  bgroup "maximumBy" []
  bgroup "minimum" []
  bgroup "minimumBy" []
  bgroup "minIndex" []
  bgroup "minIndexBy" []
  bgroup "maxIndex" []
  bgroup "maxIndexBy" []
  bgroup "foldM" []
  bgroup "ifoldM" []
  bgroup "foldM'" []
  bgroup "ifoldM'" []
  bgroup "fold1M" []
  bgroup "fold1M'" []
  bgroup "foldM_" []
  bgroup "ifoldM_" []
  bgroup "foldM'_" []
  bgroup "ifoldM'_" []
  bgroup "fold1M_" []
  bgroup "fold1M'_" []
  bgroup "sequence" []
  bgroup "sequence_" []
  bgroup "prescanl" []
  bgroup "prescanl'" []
  bgroup "postscanl" []
  bgroup "postscanl'" []
  bgroup "scanl" []
  bgroup "scanl'" []
  bgroup "scanl1" []
  bgroup "scanl1'" []
  bgroup "prescanr" []
  bgroup "postscanr" []
  bgroup "postscanr'" []
  bgroup "scanr" []
  bgroup "scanr'" []
  bgroup "scanr1" []
  bgroup "scanr1'" []
  bgroup "toList" []
  bgroup "fromList" []
  bgroup "fromListN" []
  bgroup "transient" []
  {-
   -- transient
   bgroup "length" []
   bgroup "null" []
   bgroup "slice" []
   bgroup "init" []
   bgroup "tail" []
   bgroup "take" []
   bgroup "drop" []
   bgroup "splitAt" []
   bgroup "unsafeSlice" []
   bgroup "unsafeInit" []
   bgroup "unsafeTail" []
   bgroup "unsafeTake" []
   bgroup "unsafeDrop" []
   bgroup "overlaps" []
   bgroup "new"
   bgroup "unsafeNew"
   bgroup "replicate"
   bgroup "replicateM"
   bgroup "clone"
   bgroup "grow" []
   bgroup "unsafeGrow" []
   bgroup "clear" []
   bgroup "read"
   bgroup "write"
   bgroup "modify"
   bgroup "swap"
   bgroup "unsafeRead"
   bgroup "unsafeWrite"
   bgroup "unsafeModify"
   bgroup "unsafeSwap"
   bgroup "set"
   bgroup "copy"
   bgroup "move"
   bgroup "unsafeCopy"
   bgroup "unsafeMove"
   -}
   {-
    -- rewrite rules
    -}
]

